users_email: antonio.diaz.arroyo@gmail.com;arroyo2@gmail.com
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 747954516128-b5kbjmrg5nbtboqc287h67cnfa0vp82j.apps.googleusercontent.com
            client-secret: ${client-secret}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
